# -*- coding: utf-8 -*-
"""Faith Lubin George Final Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Khpe2Da1yASnxBEBWdCnyZblwcQof2uJ
"""

pip install ucimlrepo

from ucimlrepo import fetch_ucirepo

# fetch dataset
student_performance = fetch_ucirepo(id=320)

# data (as pandas dataframes)
X = student_performance.data.features
y = student_performance.data.targets

# metadata
print(student_performance.metadata)

# variable information
print(student_performance.variables)

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
from sklearn.metrics import mean_squared_error
import seaborn as sns

df = pd.concat([X, y], axis=1)

print(df.columns.to_list())

df=df[['studytime','failures','absences','G1','G2','G3']]

X=df[['studytime','failures','absences','G1','G2']]
y=df['G3']

X=sm.add_constant(X)

X_train,X_test,y_train,y_test= train_test_split(X,y)

model= sm.OLS(y_train,X_train).fit()

prediction=model.predict(X_test)

model.summary()

mse=mean_squared_error(y_test,prediction)

mse

sns.heatmap(df.corr(),annot=True)
plt.title('Correlation Matrix')

plt.hist(df['G3'])
plt.title('Distribution of Final Grades')

plt.scatter(df['G2'],df['G3'])
plt.title('Second Period Grade(G2) vs. Final Grade(G3)')
plt.xlabel("G2")
plt.ylabel("G3")

plt.scatter(y_test,prediction)
plt.xlabel("Actual Final Grade")
plt.ylabel("Predicted Final Grade")

